### ISSUE TITLE
Problem with module behavior when configuring automatic_channel_upgrade for Kubernetes clusters

### ISSUE THREAD

**Issue by habr-mms** [telekom-mms/terraform-azurerm-container#44]
In the module, the value “stable” is set as default for automatic_channel_upgrade in locals. This conflicts with the kubernetes_version and orchestrator_version in the default_node_pool block. If the two values mentioned are not set (null), Terraform replaces them with the latest version (see https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#kubernetes_version and https:/ /registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#orchestrator_version). If the Kubernetes cluster is now updated by Azure, it will be updated to the latest version - 1 because of the "stable" specification. However, with a terraform apply, Terraform updates the cluster to the latest available version. Can the module be customized so that version information conflicts for the kubernetes cluster do not occur when Azure automatically updates it?

### Steps to reproduce:
- Create a Kubernetes cluster specifying an older version (e.g. 1.27.3).
- Leave automatic_channel_upgrade at the module standard “stable”.
- Wait until Azure updates the cluster to the current version according to update_channel (currently 1.27.7).
- Run `terraform plan`

Result:
The version information no longer matches.

Further steps:
- Remove the version information completely (set to null)
- Run `terraform plan` again

Result:
Terraform would like to update to the current latest version 1.28.3

**Comment by mikaEz** [comment]
solved with release 1.0.6
